### PR TITLE
no errors, added ci.yml

### PR DESCRIPTION
**Pull request by marcoabbrancati**
eight errors left, because class 'Horde_Db_Adapter_Pdo_Sqlite' not found

### CODE REVIEW

**Comment by ralflang** [comment]
Did you install the DB library?

**Comment by marcoabbrancati** [comment]
I declared a use statement for the class, but it was not found.

**Comment by ralflang** [comment]
That's not what I asked. You need to actually have the DB library installed to run that test.
Please wrap the test case in an if() and mark the test as skipped with reason "DB library not found"

See https://phpunit.de/manual/6.5/en/incomplete-and-skipped-tests.html for an example (but use class_exists and the actual db class, not the extension, for the check)

**Comment by marcoabbrancati** [comment]
Done, editing the test case brought no effort, if I edit the method calling the test I get an error:
Error: Class 'Horde_Log_Logger' not found
Again, creating an use statement in the participant classes doesnt change the error.
It are the same methods as before causing the error.
lg, mabbra

**Pull request merged**
